name: compile yml files into info.json
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install PyYAML dependency
      run: python3 -m pip install pyyaml
    - name: Run a one-line script
      run: python3 ./builder/jsonifier.py info src/misc/info.json
    - name: git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: add json file for commit
      run: git add src/misc/info.json
    - name: commit changed file
      run: git commit -m "Auto update info JSON file"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
