name: compile yml files into info.json
on:
  push:
    branches:
      - master

jobs:

  commit-json:
    runs-on: macos-latest
    outputs:
      filechanged: ${{ steps.checkmodjson.outputs.filechanged }}
    steps:

    - name: checkout master branch
      uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Install PyYAML dependency
      run: python3 -m pip install pyyaml

    - name: Build info.JSON file
      run: python3 ./builder/jsonifier.py info src/misc/info.json

    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Check if info.JSON was modified
      id: checkmodjson
      run: |
        git add -f src/misc/info.json
        if git status | grep -q modified
        then
          echo "::set-output name=filechanged::yes"
        else
          echo "::set-output name=filechanged::no"
        fi

    - name: Fetch project from master branch
      run: git fetch origin master

    - name: Commit changes to info.JSON
      if:
        steps.checkmodjson.outputs.filechanged == 'yes'
      run: git commit -m "Auto update info.json file"

    - name: Push changes to master branch
      if:
        steps.checkmodjson.outputs.filechanged == 'yes'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
